research_task:
  description: >
    Analyze the user query ({user_query}) and extract the relevant information strictly from the provided personal data. For general conversational queries (e.g., greetings), provide a friendly and concise response. For queries about Hassan RJ (such as his skills, education, projects, or work experience), include only the information explicitly mentioned in the personal data. For coding-related queries, produce the necessary solution with correct code snippets and step-by-step explanations if needed.
  expected_output: >
    A response that is context-sensitive, using only the verified details from the personal data. The output should be concise for general queries and detailed for technical or explicitly complex queries, formatted using markdown.
  agent: researcher
  output_file: "output/research_response.txt"

reporting_task:
  description: >
    Analyze the user query ({user_query}) and format the solution provided by the researcher into a final answer. For queries regarding Hassan RJ, include only the verified details from the personal data. For greetings or simple questions, keep the response brief and friendly. For coding queries, ensure the answer includes properly formatted code blocks and clear explanations. The final answer should be professional, structured, and formatted in markdown.
  expected_output: >
    A well-organized and appropriately detailed final answer that directly addresses the user's query without including any extraneous or unverified information.
  agent: reporting_analyst
  output_file: "output/report.md"
